using Domain.Entities.Services;

namespace Application.Features.HealthСertificatates.Responses;

public record GetLatestHealthCertificateByClientIdAndHealthCertificateTemplateIdQueryResponse(HealthCertificate? HealthCertificate);